### ISSUE TITLE
bug con pago confirmado en distintas cuentas

### ISSUE THREAD

**Issue by CristhianRF24** [combimauri/combi-events#2]
probe pagando con una cuenta y todo bien el estado cambia de manera correcta tanto en la UI como en la BD 
al registrarme con otra cuenta desde la misma pc usar la misma tarjeta realiza en registro y el pago pero el estado no cambia en la UI pero si en la BD probe con mas cuentas y pasa lo mismo

**Comment by combimauri** [comment]
Debería estar fixeado ahora, porfa lo validas y cierras el issue si es el caso.
