### ISSUE TITLE
Al registrarme a un evento y cerrar la ventana sin realizar el pago ya no puedo intentar el pago otra vez

### ISSUE THREAD

**Issue by DentVega** [combimauri/combi-events#3]
Pasos:
- Registrarme al evento
- Cerrar la pangina web
- Intentar buscar un boton para realizar el pago

**Comment by combimauri** [comment]
Debería estar fixeado ahora, porfa lo revisas y cierras este issue si es el caso

**Comment by DentVega** [comment]
Esta resuelto gracias!
